POST http://localhost:5000/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "username":"@shola2",
    "password": "olushola"
}

###

GET  http://localhost:5000/api/auth/ HTTP/1.1
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNob2xhIiwiaWF0IjoxNjc1NzM4MDAzLCJleHAiOjMzNTE0Nzk2MDZ9.X2dZQAhgBs26aaU6ClYoK9hM89WNUnRmWAQnZO7zw6w

{
    "username": "@irondraco123"
}

###
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username":"shola",
    "password": "olushola"
}

###
PUT http://localhost:5000/api/auth/update-info HTTP/1.1
Content-Type: application/json

{
    "username":"@shola",
    "password":"yongnino1"
}



